spring:
  datasource:
    url: jdbc:mysql://localhost:3306/car_data
    username: root
    password: root001
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.ervin.SuperStorm.po