spring:
  application:
    name: SuperStorm
  # Mysql
  datasource:
    name: druidDataSource
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root001
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

    #Spring Boot 默认是不注入这些属性值的，需要自己绑定
    #druid 数据源专有配置
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      #配置监控统计拦截的filters，stat:监控统计、log4j：日志记录、wall：防御sql注入
      filters: stat,wall,log4j
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

    # Spring Security
  security:
    user:
      name: root
      password: root001
      roles: admin
  # Actuator admin
#  boot:
#    admin:
#      client:
#        url: http://localhost:8082

# Mybatis
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.ervin.SuperStorm.po

# Pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
    enabled-by-default: true
  endpoint:
    health:
      show-details: always
  # prometheus
  metrics:
    tags:
      application: ${spring.application.name}
# 日志
logging:
  level:
    com:
      ervin:
        SuperStorm: debug

# 服务器
server:
  port: 8081